[system]
arch = "x86_64"
machineId = "9f3c7a2d8e1b4c6fa0d5e97b31c2a864"
hostName = "phoenix"
locale = "en_US.UTF-8"
timeZone = "Asia/Kolkata"
stateVersion = "26.05"
homeStateVersion = "26.05"

[boot]
show_logs = false


[network]
firewall = true
openTCPPorts = []
openUDPPorts = []

